language: cpp

compiler:
  - gcc

env:
  matrix:
    - LINUX=1 TE_64BITS=0  
    - WINDOWS=1 TE_64BITS=0 
    - LINUX=1 TE_64BITS=1 
    - WINDOWS=1 TE_64BITS=1 

addons:
  apt_packages:
    - pandoc


before_install:
    - travis_retry sudo apt-get update -q -y
    - if [ $LINUX ]; then if [ "$TE_64BITS" == "0" ]; then travis_retry sudo apt-get remove -q -y gvfs-daemons && travis_retry sudo apt-get install -q -y libxrandr-dev:i386 libglapi-mesa:i386 libgl1-mesa-glx:i386 libgl1-mesa-dev:i386 libxext-dev:i386 libxrender-dev:i386 g++-multilib && export CMAKE_PREFIX_PATH=/usr/lib/i386-linux-gnu; else bash -e /etc/init.d/xvfb start; fi  fi

script: rake ci

