language: cpp

compiler:
  - gcc

env:
  matrix:
    - LINUX=1   
    - WINDOWS=1 

addons:
  apt_packages:
    - pandoc

before_install:
 # CMake 2.8.12
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.tar.gz -O /tmp/cmake.tar.gz && tar -C /tmp -xvf /tmp/cmake.tar.gz && rm /tmp/cmake.tar.gz
  - cd /tmp/cmake-2.8.12 && ./bootstrap --prefix=/usr && make -j4 &&  sudo make install -j4 &&  cd - #&& rm -r /tmp/cmake-2.8.12

script: rake ci
