language: cpp

compiler:
  - gcc

env:
  global:
    - DISPLAY=:99.0
  matrix:
    - LINUX=1 TE_64BITS=0  
    - WINDOWS=1 TE_64BITS=0 
    - LINUX=1 TE_64BITS=1 
    - WINDOWS=1 TE_64BITS=1 



before_install:
    - travis_retry sudo add-apt-repository ppa:george-edison55/precise-backports -y
    - travis_retry sudo apt-get update -q -y
install:
    - travis_retry sudo apt-get install -q -y --no-install-recommends libasound2-dev
    - if [ $LINUX ]; then if [ "$TE_64BITS" == "0" ]; then travis_retry sudo apt-get remove -q -y gvfs-daemons && travis_retry sudo apt-get install -q -y libxrandr-dev:i386 libglapi-mesa:i386 libgl1-mesa-glx:i386 libgl1-mesa-dev:i386 libxext-dev:i386 libxrender-dev:i386 g++-multilib gcc-multilib && export CMAKE_PREFIX_PATH=/usr/lib/i386-linux-gnu; else bash -e /etc/init.d/xvfb start; fi; fi
    - if [ $WINDOWS ]; then if [ "$TE_64BITS" == "0" ]; then travis_retry sudo apt-get install -q -y gcc-mingw-w64-i686 g++-mingw-w64-i686 binutils-mingw-w64-i686 && export ARCH=i686; else travis_retry sudo apt-get install -q -y gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 binutils-mingw-w64-x86-64 && export ARCH=x86_64; fi && travis_retry sudo apt-get install -q -y g++-multilib gcc-multilib && export MINGW_PREFIX=/usr/bin/${ARCH}-w64-mingw32; fi

script: rake ci

