language: cpp

compiler:
  - gcc

env:
  global:
    - DISPLAY=:99.0
  matrix:
    - LINUX=1 TE_64BITS=0  
    - WINDOWS=1 TE_64BITS=0 
    - LINUX=1 TE_64BITS=1 
    - WINDOWS=1 TE_64BITS=1 



before_install:
    - travis_retry sudo apt-get update -q -y

install:

    - travis_retry sudo apt-get remove -q -y gvfs-daemons 
    - travis_retry sudo apt-get install -q -y  libice-dev:i386 libxrandr-dev:i386 libglapi-mesa:i386 libgl1-mesa-glx:i386 libgl1-mesa-dev:i386 libxext-dev:i386 libxrender-dev:i386 g++-multilib
    - travis_retry sudo apt-get autoremove
    - export CMAKE_PREFIX_PATH=/usr/lib/i386-linux-gnu
    
script: rake ci

