language: cpp

compiler:
  - gcc

env:
  matrix:
    - LINUX=1   
    - WINDOWS=1 

addons:
  apt_packages:
    - pandoc

before_install:
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake
          
script: rake ci
